// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerta.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const buscarAlertaRecente = `-- name: BuscarAlertaRecente :one
SELECT id, tipo, detalhe, criado_em FROM alerta WHERE tipo = $1 AND criado_em >= $2 ORDER BY criado_em DESC LIMIT 1
`

type BuscarAlertaRecenteParams struct {
	Tipo     string           `json:"tipo"`
	CriadoEm pgtype.Timestamp `json:"criado_em"`
}

func (q *Queries) BuscarAlertaRecente(ctx context.Context, arg BuscarAlertaRecenteParams) (Alertum, error) {
	row := q.db.QueryRow(ctx, buscarAlertaRecente, arg.Tipo, arg.CriadoEm)
	var i Alertum
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Detalhe,
		&i.CriadoEm,
	)
	return i, err
}

const contarDestinatariosDistintosDesde = `-- name: ContarDestinatariosDistintosDesde :one
SELECT count(DISTINCT c.lead_id) FROM mensagem m
JOIN conversa c ON c.id = m.conversa_id
WHERE m.direcao = 'saida' AND m.criado_em >= $1
`

// metrica do fator no 1 de banimento (secao 4.8): destinatarios distintos
// que receberam mensagem de saida numa janela recente.
func (q *Queries) ContarDestinatariosDistintosDesde(ctx context.Context, criadoEm pgtype.Timestamp) (int64, error) {
	row := q.db.QueryRow(ctx, contarDestinatariosDistintosDesde, criadoEm)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const registrarAlerta = `-- name: RegistrarAlerta :exec
INSERT INTO alerta (tipo, detalhe) VALUES ($1, $2)
`

type RegistrarAlertaParams struct {
	Tipo    string  `json:"tipo"`
	Detalhe *string `json:"detalhe"`
}

func (q *Queries) RegistrarAlerta(ctx context.Context, arg RegistrarAlertaParams) error {
	_, err := q.db.Exec(ctx, registrarAlerta, arg.Tipo, arg.Detalhe)
	return err
}
