// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerta.sql

package store

import (
	"context"
)

const buscarAlertaRecente = `-- name: BuscarAlertaRecente :one
SELECT id, tipo, detalhe, criado_em FROM alerta
WHERE tipo = $1
  AND criado_em >= LOCALTIMESTAMP - make_interval(secs => $2::double precision)
ORDER BY criado_em DESC
LIMIT 1
`

type BuscarAlertaRecenteParams struct {
	Tipo           string  `json:"tipo"`
	JanelaSegundos float64 `json:"janela_segundos"`
}

func (q *Queries) BuscarAlertaRecente(ctx context.Context, arg BuscarAlertaRecenteParams) (Alertum, error) {
	row := q.db.QueryRow(ctx, buscarAlertaRecente, arg.Tipo, arg.JanelaSegundos)
	var i Alertum
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Detalhe,
		&i.CriadoEm,
	)
	return i, err
}

const contarDestinatariosDistintosNaJanela = `-- name: ContarDestinatariosDistintosNaJanela :one
SELECT count(DISTINCT c.lead_id) FROM mensagem m
JOIN conversa c ON c.id = m.conversa_id
WHERE m.direcao = 'saida'
  AND m.criado_em >= LOCALTIMESTAMP - make_interval(secs => $1::double precision)
`

// metrica do fator no 1 de banimento (secao 4.8): destinatarios distintos
// que receberam mensagem de saida numa janela recente.
// a janela e resolvida no relogio do banco (LOCALTIMESTAMP), nao no Go --
// criado_em nasce de DEFAULT LOCALTIMESTAMP, entao os dois lados da
// comparacao tem de vir do mesmo relogio (P1-08). Com o Go mandando o
// corte pronto, uma diferenca de 3h transformava a janela de 60min em
// "nada" ou em "quase 4h".
func (q *Queries) ContarDestinatariosDistintosNaJanela(ctx context.Context, janelaSegundos float64) (int64, error) {
	row := q.db.QueryRow(ctx, contarDestinatariosDistintosNaJanela, janelaSegundos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const registrarAlerta = `-- name: RegistrarAlerta :exec
INSERT INTO alerta (tipo, detalhe) VALUES ($1, $2)
`

type RegistrarAlertaParams struct {
	Tipo    string  `json:"tipo"`
	Detalhe *string `json:"detalhe"`
}

func (q *Queries) RegistrarAlerta(ctx context.Context, arg RegistrarAlertaParams) error {
	_, err := q.db.Exec(ctx, registrarAlerta, arg.Tipo, arg.Detalhe)
	return err
}
