// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: aplicacao.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const buscarAplicacaoPorCodigo = `-- name: BuscarAplicacaoPorCodigo :one
SELECT id, codigo, nome, ativo, criado_em
FROM aplicacao
WHERE codigo = $1
`

type BuscarAplicacaoPorCodigoRow struct {
	ID       int64            `json:"id"`
	Codigo   string           `json:"codigo"`
	Nome     string           `json:"nome"`
	Ativo    bool             `json:"ativo"`
	CriadoEm pgtype.Timestamp `json:"criado_em"`
}

func (q *Queries) BuscarAplicacaoPorCodigo(ctx context.Context, codigo string) (BuscarAplicacaoPorCodigoRow, error) {
	row := q.db.QueryRow(ctx, buscarAplicacaoPorCodigo, codigo)
	var i BuscarAplicacaoPorCodigoRow
	err := row.Scan(
		&i.ID,
		&i.Codigo,
		&i.Nome,
		&i.Ativo,
		&i.CriadoEm,
	)
	return i, err
}

const buscarAplicacaoPorTokenHash = `-- name: BuscarAplicacaoPorTokenHash :one
SELECT id, codigo, nome, ativo, token_hash
FROM aplicacao
WHERE token_hash = $1
  AND ativo
`

type BuscarAplicacaoPorTokenHashRow struct {
	ID        int64  `json:"id"`
	Codigo    string `json:"codigo"`
	Nome      string `json:"nome"`
	Ativo     bool   `json:"ativo"`
	TokenHash string `json:"token_hash"`
}

// Autenticacao de servico (fase 1 do barramento). Filtra por ativo aqui e
// nao no Go: desativar uma aplicacao tem que bloquea-la mesmo que algum
// caminho novo esqueca de checar o campo.
//
// O hash e a chave de busca, entao o token em claro nunca sai do processo
// que o recebeu -- nao ha SELECT por token, nem token em log de query.
//
// token_hash volta no SELECT para o Go refazer a comparacao em tempo
// constante (crypto/subtle). Parece redundante -- o WHERE ja compara --
// mas a igualdade do Postgres depende de collation e para em curto-
// circuito no primeiro byte diferente; refazer no Go custa nada e tira o
// unico ponto de comparacao de segredo de fora do nosso controle.
func (q *Queries) BuscarAplicacaoPorTokenHash(ctx context.Context, tokenHash string) (BuscarAplicacaoPorTokenHashRow, error) {
	row := q.db.QueryRow(ctx, buscarAplicacaoPorTokenHash, tokenHash)
	var i BuscarAplicacaoPorTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.Codigo,
		&i.Nome,
		&i.Ativo,
		&i.TokenHash,
	)
	return i, err
}

const listarAplicacoes = `-- name: ListarAplicacoes :many
SELECT id, codigo, nome, ativo, criado_em
FROM aplicacao
ORDER BY codigo
`

type ListarAplicacoesRow struct {
	ID       int64            `json:"id"`
	Codigo   string           `json:"codigo"`
	Nome     string           `json:"nome"`
	Ativo    bool             `json:"ativo"`
	CriadoEm pgtype.Timestamp `json:"criado_em"`
}

func (q *Queries) ListarAplicacoes(ctx context.Context) ([]ListarAplicacoesRow, error) {
	rows, err := q.db.Query(ctx, listarAplicacoes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarAplicacoesRow
	for rows.Next() {
		var i ListarAplicacoesRow
		if err := rows.Scan(
			&i.ID,
			&i.Codigo,
			&i.Nome,
			&i.Ativo,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sincronizarTokenAplicacao = `-- name: SincronizarTokenAplicacao :one
INSERT INTO aplicacao (codigo, nome, token_hash)
VALUES ($1, $2, $3)
ON CONFLICT (codigo) DO UPDATE SET token_hash = EXCLUDED.token_hash
RETURNING id, codigo, nome, ativo
`

type SincronizarTokenAplicacaoParams struct {
	Codigo    string `json:"codigo"`
	Nome      string `json:"nome"`
	TokenHash string `json:"token_hash"`
}

type SincronizarTokenAplicacaoRow struct {
	ID     int64  `json:"id"`
	Codigo string `json:"codigo"`
	Nome   string `json:"nome"`
	Ativo  bool   `json:"ativo"`
}

// Upsert usado na subida para a aplicacao 'crm' herdar o
// GATEWAY_SERVICE_TOKEN atual (a migration nao le ambiente, e o segredo
// nao pode ficar versionado). Idempotente: subir duas vezes com o mesmo
// token nao muda nada.
func (q *Queries) SincronizarTokenAplicacao(ctx context.Context, arg SincronizarTokenAplicacaoParams) (SincronizarTokenAplicacaoRow, error) {
	row := q.db.QueryRow(ctx, sincronizarTokenAplicacao, arg.Codigo, arg.Nome, arg.TokenHash)
	var i SincronizarTokenAplicacaoRow
	err := row.Scan(
		&i.ID,
		&i.Codigo,
		&i.Nome,
		&i.Ativo,
	)
	return i, err
}
