// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auditoria.sql

package store

import (
	"context"
)

const atualizarHashMensagem = `-- name: AtualizarHashMensagem :exec
UPDATE mensagem SET hash_anterior = $2, hash = $3 WHERE id = $1
`

type AtualizarHashMensagemParams struct {
	ID           int64   `json:"id"`
	HashAnterior *string `json:"hash_anterior"`
	Hash         *string `json:"hash"`
}

func (q *Queries) AtualizarHashMensagem(ctx context.Context, arg AtualizarHashMensagemParams) error {
	_, err := q.db.Exec(ctx, atualizarHashMensagem, arg.ID, arg.HashAnterior, arg.Hash)
	return err
}

const travarUltimoHashAuditoria = `-- name: TravarUltimoHashAuditoria :one
SELECT valor FROM parametro WHERE chave = $1 FOR UPDATE
`

// FOR UPDATE serializa concorrencia entre webhook (entrada) e /api/mensagens
// (saida) escrevendo na cadeia ao mesmo tempo -- sem isso os dois podem ler
// o mesmo hash_anterior e produzir dois elos concorrentes (fase 12).
func (q *Queries) TravarUltimoHashAuditoria(ctx context.Context, chave string) (*string, error) {
	row := q.db.QueryRow(ctx, travarUltimoHashAuditoria, chave)
	var valor *string
	err := row.Scan(&valor)
	return valor, err
}
