// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: caixa.sql

package store

import (
	"context"
)

const codigoDaCaixa = `-- name: CodigoDaCaixa :one
SELECT codigo FROM caixa WHERE id = $1
`

func (q *Queries) CodigoDaCaixa(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, codigoDaCaixa, id)
	var codigo string
	err := row.Scan(&codigo)
	return codigo, err
}

const listarCaixasAtivas = `-- name: ListarCaixasAtivas :many

SELECT id, codigo, nome, provedor, instancia_id, instancia_token, client_token, webhook_segredo, ativo, criado_em FROM caixa WHERE ativo ORDER BY id
`

// G1 (docs/PLANO_MULTICAIXA_E_CONVERSAS.md): uma caixa por numero.
func (q *Queries) ListarCaixasAtivas(ctx context.Context) ([]Caixa, error) {
	rows, err := q.db.Query(ctx, listarCaixasAtivas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Caixa
	for rows.Next() {
		var i Caixa
		if err := rows.Scan(
			&i.ID,
			&i.Codigo,
			&i.Nome,
			&i.Provedor,
			&i.InstanciaID,
			&i.InstanciaToken,
			&i.ClientToken,
			&i.WebhookSegredo,
			&i.Ativo,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sincronizarCaixaSemente = `-- name: SincronizarCaixaSemente :exec
INSERT INTO caixa (codigo, nome, provedor, instancia_id, instancia_token, client_token, webhook_segredo)
VALUES (
    $1,
    $1,
    'zapi',
    NULLIF($2::text, ''),
    NULLIF($3::text, ''),
    NULLIF($4::text, ''),
    COALESCE(NULLIF($5::text, ''), replace(gen_random_uuid()::text, '-', ''))
)
ON CONFLICT (codigo) DO UPDATE
   SET instancia_id    = COALESCE(NULLIF($2::text, ''), caixa.instancia_id),
       instancia_token = COALESCE(NULLIF($3::text, ''), caixa.instancia_token),
       client_token    = COALESCE(NULLIF($4::text, ''), caixa.client_token),
       webhook_segredo = COALESCE(NULLIF($5::text, ''), caixa.webhook_segredo)
`

type SincronizarCaixaSementeParams struct {
	Codigo         string `json:"codigo"`
	InstanciaID    string `json:"instancia_id"`
	InstanciaToken string `json:"instancia_token"`
	ClientToken    string `json:"client_token"`
	WebhookSegredo string `json:"webhook_segredo"`
}

// A caixa semente tem o .env como origem: a subida grava nela o que estiver
// preenchido e nao apaga o que estiver vazio -- .env sem credencial (dev
// sem z-api) nao pode zerar a caixa cadastrada no banco.
func (q *Queries) SincronizarCaixaSemente(ctx context.Context, arg SincronizarCaixaSementeParams) error {
	_, err := q.db.Exec(ctx, sincronizarCaixaSemente,
		arg.Codigo,
		arg.InstanciaID,
		arg.InstanciaToken,
		arg.ClientToken,
		arg.WebhookSegredo,
	)
	return err
}
