// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: canal.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const buscarCanal = `-- name: BuscarCanal :one
SELECT id, aplicacao_id, canal_externo, criado_em
FROM canal
WHERE aplicacao_id = $1
  AND canal_externo = $2
`

type BuscarCanalParams struct {
	AplicacaoID  int64  `json:"aplicacao_id"`
	CanalExterno string `json:"canal_externo"`
}

func (q *Queries) BuscarCanal(ctx context.Context, arg BuscarCanalParams) (Canal, error) {
	row := q.db.QueryRow(ctx, buscarCanal, arg.AplicacaoID, arg.CanalExterno)
	var i Canal
	err := row.Scan(
		&i.ID,
		&i.AplicacaoID,
		&i.CanalExterno,
		&i.CriadoEm,
	)
	return i, err
}

const listarAssinantes = `-- name: ListarAssinantes :many
SELECT ca.destino_externo, ca.criado_em
FROM canal_assinante ca
JOIN canal c ON c.id = ca.canal_id
WHERE c.aplicacao_id = $1
  AND c.canal_externo = $2
ORDER BY ca.destino_externo
`

type ListarAssinantesParams struct {
	AplicacaoID  int64  `json:"aplicacao_id"`
	CanalExterno string `json:"canal_externo"`
}

type ListarAssinantesRow struct {
	DestinoExterno string           `json:"destino_externo"`
	CriadoEm       pgtype.Timestamp `json:"criado_em"`
}

func (q *Queries) ListarAssinantes(ctx context.Context, arg ListarAssinantesParams) ([]ListarAssinantesRow, error) {
	rows, err := q.db.Query(ctx, listarAssinantes, arg.AplicacaoID, arg.CanalExterno)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarAssinantesRow
	for rows.Next() {
		var i ListarAssinantesRow
		if err := rows.Scan(&i.DestinoExterno, &i.CriadoEm); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarChavesDeEntregaDoCanal = `-- name: ListarChavesDeEntregaDoCanal :many
SELECT (a.codigo || ':' || ca.destino_externo)::text AS chave
FROM canal_assinante ca
JOIN canal c     ON c.id = ca.canal_id
JOIN aplicacao a ON a.id = c.aplicacao_id
WHERE ca.canal_id = $1
`

// Chaves do hub ("aplicacao:destino") para um canal, por ID.
//
// Monta a chave no SQL porque quem publica (fase 5 em diante) so tem o id
// do canal e nao deve precisar consultar a aplicacao de novo so para
// prefixar. A composicao tem que casar exatamente com sse.ChaveDestino --
// se divergir, o evento e publicado numa chave que ninguem assina e a
// entrega some em silencio.
// O ::text nao e decorativo: sem ele o sqlc nao sabe o tipo da
// concatenacao e gera []interface{}, que so estoura na primeira vez que
// alguem tenta usar a lista de verdade (foi o que aconteceu na fase 5).
func (q *Queries) ListarChavesDeEntregaDoCanal(ctx context.Context, canalID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listarChavesDeEntregaDoCanal, canalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var chave string
		if err := rows.Scan(&chave); err != nil {
			return nil, err
		}
		items = append(items, chave)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removerAssinante = `-- name: RemoverAssinante :execrows
DELETE FROM canal_assinante ca
USING canal c
WHERE ca.canal_id = c.id
  AND c.aplicacao_id = $1
  AND c.canal_externo = $2
  AND ca.destino_externo = $3
`

type RemoverAssinanteParams struct {
	AplicacaoID    int64  `json:"aplicacao_id"`
	CanalExterno   string `json:"canal_externo"`
	DestinoExterno string `json:"destino_externo"`
}

// Devolve o numero de linhas para o handler distinguir "removido agora" de
// "nao estava la" -- os dois respondem 204, mas so o primeiro merece log.
func (q *Queries) RemoverAssinante(ctx context.Context, arg RemoverAssinanteParams) (int64, error) {
	result, err := q.db.Exec(ctx, removerAssinante, arg.AplicacaoID, arg.CanalExterno, arg.DestinoExterno)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAssinante = `-- name: UpsertAssinante :exec
INSERT INTO canal_assinante (canal_id, destino_externo)
SELECT c.id, $1
FROM canal c
WHERE c.aplicacao_id = $2
  AND c.canal_externo = $3
ON CONFLICT (canal_id, destino_externo) DO NOTHING
`

type UpsertAssinanteParams struct {
	DestinoExterno string `json:"destino_externo"`
	AplicacaoID    int64  `json:"aplicacao_id"`
	CanalExterno   string `json:"canal_externo"`
}

// Idempotente. O canal_id vem de uma subconsulta escopada em vez de
// parametro direto: assim nem um id de canal de outra aplicacao,
// adivinhado ou vazado, consegue inserir assinante aqui.
func (q *Queries) UpsertAssinante(ctx context.Context, arg UpsertAssinanteParams) error {
	_, err := q.db.Exec(ctx, upsertAssinante, arg.DestinoExterno, arg.AplicacaoID, arg.CanalExterno)
	return err
}

const upsertCanal = `-- name: UpsertCanal :one

INSERT INTO canal (aplicacao_id, canal_externo)
VALUES ($1, $2)
ON CONFLICT (aplicacao_id, canal_externo)
    DO UPDATE SET canal_externo = EXCLUDED.canal_externo
RETURNING id, aplicacao_id, canal_externo, criado_em
`

type UpsertCanalParams struct {
	AplicacaoID  int64  `json:"aplicacao_id"`
	CanalExterno string `json:"canal_externo"`
}

// Barramento, fase 4. TODA query aqui e escopada por aplicacao_id -- uma
// aplicacao nunca le nem escreve canal de outra.
//
// O escopo esta no WHERE de cada query, e nao numa checagem no Go, de
// proposito: uma checagem esquecida num handler novo vaza; um WHERE que
// nao existe faz a query devolver zero linhas, que e o lado seguro do
// erro.
// Idempotente: PUT repetido confirma em vez de duplicar. O DO UPDATE toca
// a propria coluna para que o RETURNING traga a linha tambem quando ela ja
// existia -- com DO NOTHING o insert conflitante nao retorna nada, e o
// handler teria de fazer um SELECT extra so para descobrir o id.
func (q *Queries) UpsertCanal(ctx context.Context, arg UpsertCanalParams) (Canal, error) {
	row := q.db.QueryRow(ctx, upsertCanal, arg.AplicacaoID, arg.CanalExterno)
	var i Canal
	err := row.Scan(
		&i.ID,
		&i.AplicacaoID,
		&i.CanalExterno,
		&i.CriadoEm,
	)
	return i, err
}
