// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chatinterno.sql

package store

import (
	"context"
)

const buscarUltimoIDMensagemInterna = `-- name: BuscarUltimoIDMensagemInterna :one
SELECT COALESCE(MAX(id), 0)::bigint FROM mensagem_interna
`

// ponto de partida do poller no start (fase 10) -- sem isso, todo o
// historico de mensagem_interna reapareceria como "nova" a cada restart.
func (q *Queries) BuscarUltimoIDMensagemInterna(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, buscarUltimoIDMensagemInterna)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listarMensagensInternasAPartirDe = `-- name: ListarMensagensInternasAPartirDe :many
SELECT id, canal_id, usuario_id, texto, criado_em
FROM mensagem_interna
WHERE id > $1
ORDER BY id
`

// mensagem_interna e escrita direto pelo crm, sem passar pelo gateway
// (secao 6) -- o poller so enxerga linha nova comparando id.
func (q *Queries) ListarMensagensInternasAPartirDe(ctx context.Context, id int64) ([]MensagemInterna, error) {
	rows, err := q.db.Query(ctx, listarMensagensInternasAPartirDe, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MensagemInterna
	for rows.Next() {
		var i MensagemInterna
		if err := rows.Scan(
			&i.ID,
			&i.CanalID,
			&i.UsuarioID,
			&i.Texto,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
