// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversa_v1.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const buscarConversaComContatoPorID = `-- name: BuscarConversaComContatoPorID :one

SELECT c.id, c.aberta_em, c.fechada_em, cx.codigo AS caixa,
       l.nome AS contato_nome, l.telefone_e164 AS contato_telefone, l.chat_lid AS contato_chat_lid
  FROM conversa c
  JOIN caixa cx ON cx.id = c.caixa_id
  JOIN lead l ON l.id = c.lead_id
 WHERE c.id = $1
`

type BuscarConversaComContatoPorIDRow struct {
	ID              int64            `json:"id"`
	AbertaEm        pgtype.Timestamp `json:"aberta_em"`
	FechadaEm       pgtype.Timestamp `json:"fechada_em"`
	Caixa           string           `json:"caixa"`
	ContatoNome     *string          `json:"contato_nome"`
	ContatoTelefone *string          `json:"contato_telefone"`
	ContatoChatLid  *string          `json:"contato_chat_lid"`
}

// G2/G3 do barramento (docs/PLANO_MULTICAIXA_E_CONVERSAS.md): API de
// leitura de conversa e mensagem de WhatsApp para o portal. Devolver o
// que o gateway mesmo gravou nao e consulta de dominio da aplicacao (ver
// "o teste de contrato" no plano) -- por isso mora aqui e nao atras de
// if de aplicacao nenhum.
// usada pelos dois endpoints (lista precisa do contato de cada linha,
// GET .../mensagens precisa confirmar que a conversa existe antes de
// listar). corretor_id fica de fora -- e divida legada (D2 do plano),
// nao entra em contrato novo.
func (q *Queries) BuscarConversaComContatoPorID(ctx context.Context, id int64) (BuscarConversaComContatoPorIDRow, error) {
	row := q.db.QueryRow(ctx, buscarConversaComContatoPorID, id)
	var i BuscarConversaComContatoPorIDRow
	err := row.Scan(
		&i.ID,
		&i.AbertaEm,
		&i.FechadaEm,
		&i.Caixa,
		&i.ContatoNome,
		&i.ContatoTelefone,
		&i.ContatoChatLid,
	)
	return i, err
}

const listarConversas = `-- name: ListarConversas :many
WITH ultima_por_conversa AS (
    SELECT DISTINCT ON (m.conversa_id)
           m.conversa_id, m.id, m.direcao, m.tipo, m.texto, m.status, m.criado_em
      FROM mensagem m
     ORDER BY m.conversa_id, m.criado_em DESC, m.id DESC
)
SELECT
    c.id,
    cx.codigo AS caixa,
    c.aberta_em,
    c.fechada_em,
    l.nome AS contato_nome,
    l.telefone_e164 AS contato_telefone,
    l.chat_lid AS contato_chat_lid,
    ultima.id AS ultima_mensagem_id,
    ultima.direcao AS ultima_mensagem_direcao,
    ultima.tipo AS ultima_mensagem_tipo,
    ultima.texto AS ultima_mensagem_texto,
    ultima.status AS ultima_mensagem_status,
    COALESCE(ultima.criado_em, c.aberta_em) AS ultima_atividade,
    -- G6: entrada acima da ultima leitura DESTA aplicacao. Subquery escalar
    -- aqui e segura para o sqlc porque count(*) nunca e NULL, e o Postgres
    -- so a avalia para as linhas que sobram do LIMIT.
    (SELECT count(*)
       FROM mensagem mn
      WHERE mn.conversa_id = c.id
        AND mn.direcao = 'entrada'
        AND mn.id > COALESCE((SELECT cl.ultima_lida_id
                                FROM conversa_leitura cl
                               WHERE cl.conversa_id = c.id
                                 AND cl.aplicacao_id = $1::bigint), 0)
    )::int AS nao_lidas
FROM conversa c
JOIN caixa cx ON cx.id = c.caixa_id
JOIN lead l ON l.id = c.lead_id
LEFT JOIN ultima_por_conversa ultima ON ultima.conversa_id = c.id
WHERE
    -- G1: caixa nula = todas.
    ($2::bigint IS NULL OR c.caixa_id = $2::bigint)
    AND (
        $3::text = 'todas'
        OR ($3::text = 'abertas' AND c.fechada_em IS NULL)
        OR ($3::text = 'fechadas' AND c.fechada_em IS NOT NULL)
    )
    AND (
        $4::timestamp IS NULL
        OR COALESCE(ultima.criado_em, c.aberta_em) >= $4::timestamp
    )
    AND (
        $5::timestamp IS NULL
        OR (COALESCE(ultima.criado_em, c.aberta_em), c.id) < ($5::timestamp, $6::bigint)
    )
ORDER BY ultima_atividade DESC, c.id DESC
LIMIT $7
`

type ListarConversasParams struct {
	AplicacaoID     int64            `json:"aplicacao_id"`
	CaixaID         *int64           `json:"caixa_id"`
	Estado          string           `json:"estado"`
	Desde           pgtype.Timestamp `json:"desde"`
	CursorAtividade pgtype.Timestamp `json:"cursor_atividade"`
	CursorID        *int64           `json:"cursor_id"`
	Limite          int32            `json:"limite"`
}

type ListarConversasRow struct {
	ID                    int64            `json:"id"`
	Caixa                 string           `json:"caixa"`
	AbertaEm              pgtype.Timestamp `json:"aberta_em"`
	FechadaEm             pgtype.Timestamp `json:"fechada_em"`
	ContatoNome           *string          `json:"contato_nome"`
	ContatoTelefone       *string          `json:"contato_telefone"`
	ContatoChatLid        *string          `json:"contato_chat_lid"`
	UltimaMensagemID      *int64           `json:"ultima_mensagem_id"`
	UltimaMensagemDirecao *string          `json:"ultima_mensagem_direcao"`
	UltimaMensagemTipo    *string          `json:"ultima_mensagem_tipo"`
	UltimaMensagemTexto   *string          `json:"ultima_mensagem_texto"`
	UltimaMensagemStatus  *string          `json:"ultima_mensagem_status"`
	UltimaAtividade       pgtype.Timestamp `json:"ultima_atividade"`
	NaoLidas              int32            `json:"nao_lidas"`
}

// "ultima_atividade" e a hora da mensagem mais recente da conversa, ou
// aberta_em quando ainda nao ha nenhuma -- e o criterio de ordenacao (mais
// recente primeiro) e de paginacao por cursor.
//
// ultima_por_conversa e um LEFT JOIN comum com uma tabela derivada, e nao
// LATERAL nem subquery escalar por coluna: o sqlc (analise estatica, sem
// round-trip ao banco) so reconhece nulabilidade de coluna vinda de LEFT
// JOIN quando o lado direito e uma relacao "normal" -- com LATERAL ou
// subquery por coluna ele gera campo Go NAO-ponteiro para uma coluna que
// pode vir NULL, e pgx quebra o Scan na primeira conversa sem mensagem
// (conferido em teste de integracao). DISTINCT ON com a mesma
// mensagem_conversa_criado_em_idx (migration 00011) evita o agregado
// sobre a tabela inteira.
func (q *Queries) ListarConversas(ctx context.Context, arg ListarConversasParams) ([]ListarConversasRow, error) {
	rows, err := q.db.Query(ctx, listarConversas,
		arg.AplicacaoID,
		arg.CaixaID,
		arg.Estado,
		arg.Desde,
		arg.CursorAtividade,
		arg.CursorID,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarConversasRow
	for rows.Next() {
		var i ListarConversasRow
		if err := rows.Scan(
			&i.ID,
			&i.Caixa,
			&i.AbertaEm,
			&i.FechadaEm,
			&i.ContatoNome,
			&i.ContatoTelefone,
			&i.ContatoChatLid,
			&i.UltimaMensagemID,
			&i.UltimaMensagemDirecao,
			&i.UltimaMensagemTipo,
			&i.UltimaMensagemTexto,
			&i.UltimaMensagemStatus,
			&i.UltimaAtividade,
			&i.NaoLidas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarMensagensDaConversa = `-- name: ListarMensagensDaConversa :many
SELECT id, direcao, tipo, texto, midia_caminho, status, criado_em
  FROM mensagem
 WHERE conversa_id = $1
   AND id > $2
   AND ($3::bigint IS NULL OR id < $3::bigint)
 ORDER BY id
 LIMIT $4
`

type ListarMensagensDaConversaParams struct {
	ConversaID int64  `json:"conversa_id"`
	DesdeID    int64  `json:"desde_id"`
	AteID      *int64 `json:"ate_id"`
	Limite     int32  `json:"limite"`
}

type ListarMensagensDaConversaRow struct {
	ID           int64            `json:"id"`
	Direcao      string           `json:"direcao"`
	Tipo         string           `json:"tipo"`
	Texto        *string          `json:"texto"`
	MidiaCaminho *string          `json:"midia_caminho"`
	Status       string           `json:"status"`
	CriadoEm     pgtype.Timestamp `json:"criado_em"`
}

// Mesmo contrato do historico do canal interno (secao G2/G3 do plano):
// desde_id/limite, ordem crescente, ultimo_id pronto para a proxima
// pagina. ate_id (nulavel) pagina PARA TRAS, para a rolagem infinita da
// timeline ao abrir uma conversa antiga.
func (q *Queries) ListarMensagensDaConversa(ctx context.Context, arg ListarMensagensDaConversaParams) ([]ListarMensagensDaConversaRow, error) {
	rows, err := q.db.Query(ctx, listarMensagensDaConversa,
		arg.ConversaID,
		arg.DesdeID,
		arg.AteID,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarMensagensDaConversaRow
	for rows.Next() {
		var i ListarMensagensDaConversaRow
		if err := rows.Scan(
			&i.ID,
			&i.Direcao,
			&i.Tipo,
			&i.Texto,
			&i.MidiaCaminho,
			&i.Status,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marcarConversaLida = `-- name: MarcarConversaLida :execrows
INSERT INTO conversa_leitura (aplicacao_id, conversa_id, ultima_lida_id)
SELECT $1::bigint, c.id,
       COALESCE($2::bigint, (SELECT max(m.id) FROM mensagem m WHERE m.conversa_id = c.id))
  FROM conversa c
 WHERE c.id = $3::bigint
   AND COALESCE($2::bigint, (SELECT max(m.id) FROM mensagem m WHERE m.conversa_id = c.id)) IS NOT NULL
ON CONFLICT (aplicacao_id, conversa_id) DO UPDATE
   SET ultima_lida_id = GREATEST(conversa_leitura.ultima_lida_id, EXCLUDED.ultima_lida_id),
       atualizado_em  = now()
`

type MarcarConversaLidaParams struct {
	AplicacaoID int64  `json:"aplicacao_id"`
	AteID       *int64 `json:"ate_id"`
	ConversaID  int64  `json:"conversa_id"`
}

// G6. ate_id nulo = ate a ultima mensagem da conversa. GREATEST porque
// leitura nao retrocede: duas abas marcando fora de ordem nao podem fazer
// o badge reaparecer. Conversa sem mensagem nao grava nada (0 linhas).
func (q *Queries) MarcarConversaLida(ctx context.Context, arg MarcarConversaLidaParams) (int64, error) {
	result, err := q.db.Exec(ctx, marcarConversaLida, arg.AplicacaoID, arg.AteID, arg.ConversaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const preencherNomeDoLeadSeVazio = `-- name: PreencherNomeDoLeadSeVazio :exec
UPDATE lead SET nome = $1 WHERE id = $2 AND (nome IS NULL OR nome = '')
`

type PreencherNomeDoLeadSeVazioParams struct {
	Nome *string `json:"nome"`
	ID   int64   `json:"id"`
}

// G4. O nome informado por quem abre a conversa so vale para lead sem nome:
// o nome de perfil que o WhatsApp mandou antes continua sendo o dado.
func (q *Queries) PreencherNomeDoLeadSeVazio(ctx context.Context, arg PreencherNomeDoLeadSeVazioParams) error {
	_, err := q.db.Exec(ctx, preencherNomeDoLeadSeVazio, arg.Nome, arg.ID)
	return err
}

const travarIdentidadeDoContato = `-- name: TravarIdentidadeDoContato :exec
SELECT pg_advisory_xact_lock(hashtext('abrir_conversa:' || $1::text))
`

// G4. Serializa a abertura de conversa por telefone dentro da transacao:
// lead.telefone_e164 nao tem indice unico, entao duas aberturas simultaneas
// para o mesmo numero criariam dois leads e partiriam o historico.
func (q *Queries) TravarIdentidadeDoContato(ctx context.Context, telefoneE164 string) error {
	_, err := q.db.Exec(ctx, travarIdentidadeDoContato, telefoneE164)
	return err
}
