// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversa_v1.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const buscarConversaComContatoPorID = `-- name: BuscarConversaComContatoPorID :one

SELECT c.id, c.aberta_em, c.fechada_em,
       l.nome AS contato_nome, l.telefone_e164 AS contato_telefone, l.chat_lid AS contato_chat_lid
  FROM conversa c
  JOIN lead l ON l.id = c.lead_id
 WHERE c.id = $1
`

type BuscarConversaComContatoPorIDRow struct {
	ID              int64            `json:"id"`
	AbertaEm        pgtype.Timestamp `json:"aberta_em"`
	FechadaEm       pgtype.Timestamp `json:"fechada_em"`
	ContatoNome     *string          `json:"contato_nome"`
	ContatoTelefone *string          `json:"contato_telefone"`
	ContatoChatLid  *string          `json:"contato_chat_lid"`
}

// G2/G3 do barramento (docs/PLANO_MULTICAIXA_E_CONVERSAS.md): API de
// leitura de conversa e mensagem de WhatsApp para o portal. Devolver o
// que o gateway mesmo gravou nao e consulta de dominio da aplicacao (ver
// "o teste de contrato" no plano) -- por isso mora aqui e nao atras de
// if de aplicacao nenhum.
// usada pelos dois endpoints (lista precisa do contato de cada linha,
// GET .../mensagens precisa confirmar que a conversa existe antes de
// listar). corretor_id fica de fora -- e divida legada (D2 do plano),
// nao entra em contrato novo.
func (q *Queries) BuscarConversaComContatoPorID(ctx context.Context, id int64) (BuscarConversaComContatoPorIDRow, error) {
	row := q.db.QueryRow(ctx, buscarConversaComContatoPorID, id)
	var i BuscarConversaComContatoPorIDRow
	err := row.Scan(
		&i.ID,
		&i.AbertaEm,
		&i.FechadaEm,
		&i.ContatoNome,
		&i.ContatoTelefone,
		&i.ContatoChatLid,
	)
	return i, err
}

const listarConversas = `-- name: ListarConversas :many
WITH ultima_por_conversa AS (
    SELECT DISTINCT ON (m.conversa_id)
           m.conversa_id, m.id, m.direcao, m.tipo, m.texto, m.status, m.criado_em
      FROM mensagem m
     ORDER BY m.conversa_id, m.criado_em DESC, m.id DESC
)
SELECT
    c.id,
    c.aberta_em,
    c.fechada_em,
    l.nome AS contato_nome,
    l.telefone_e164 AS contato_telefone,
    l.chat_lid AS contato_chat_lid,
    ultima.id AS ultima_mensagem_id,
    ultima.direcao AS ultima_mensagem_direcao,
    ultima.tipo AS ultima_mensagem_tipo,
    ultima.texto AS ultima_mensagem_texto,
    ultima.status AS ultima_mensagem_status,
    COALESCE(ultima.criado_em, c.aberta_em) AS ultima_atividade
FROM conversa c
JOIN lead l ON l.id = c.lead_id
LEFT JOIN ultima_por_conversa ultima ON ultima.conversa_id = c.id
WHERE
    (
        $1::text = 'todas'
        OR ($1::text = 'abertas' AND c.fechada_em IS NULL)
        OR ($1::text = 'fechadas' AND c.fechada_em IS NOT NULL)
    )
    AND (
        $2::timestamp IS NULL
        OR COALESCE(ultima.criado_em, c.aberta_em) >= $2::timestamp
    )
    AND (
        $3::timestamp IS NULL
        OR (COALESCE(ultima.criado_em, c.aberta_em), c.id) < ($3::timestamp, $4::bigint)
    )
ORDER BY ultima_atividade DESC, c.id DESC
LIMIT $5
`

type ListarConversasParams struct {
	Estado          string           `json:"estado"`
	Desde           pgtype.Timestamp `json:"desde"`
	CursorAtividade pgtype.Timestamp `json:"cursor_atividade"`
	CursorID        *int64           `json:"cursor_id"`
	Limite          int32            `json:"limite"`
}

type ListarConversasRow struct {
	ID                    int64            `json:"id"`
	AbertaEm              pgtype.Timestamp `json:"aberta_em"`
	FechadaEm             pgtype.Timestamp `json:"fechada_em"`
	ContatoNome           *string          `json:"contato_nome"`
	ContatoTelefone       *string          `json:"contato_telefone"`
	ContatoChatLid        *string          `json:"contato_chat_lid"`
	UltimaMensagemID      *int64           `json:"ultima_mensagem_id"`
	UltimaMensagemDirecao *string          `json:"ultima_mensagem_direcao"`
	UltimaMensagemTipo    *string          `json:"ultima_mensagem_tipo"`
	UltimaMensagemTexto   *string          `json:"ultima_mensagem_texto"`
	UltimaMensagemStatus  *string          `json:"ultima_mensagem_status"`
	UltimaAtividade       pgtype.Timestamp `json:"ultima_atividade"`
}

// "ultima_atividade" e a hora da mensagem mais recente da conversa, ou
// aberta_em quando ainda nao ha nenhuma -- e o criterio de ordenacao (mais
// recente primeiro) e de paginacao por cursor.
//
// ultima_por_conversa e um LEFT JOIN comum com uma tabela derivada, e nao
// LATERAL nem subquery escalar por coluna: o sqlc (analise estatica, sem
// round-trip ao banco) so reconhece nulabilidade de coluna vinda de LEFT
// JOIN quando o lado direito e uma relacao "normal" -- com LATERAL ou
// subquery por coluna ele gera campo Go NAO-ponteiro para uma coluna que
// pode vir NULL, e pgx quebra o Scan na primeira conversa sem mensagem
// (conferido em teste de integracao). DISTINCT ON com a mesma
// mensagem_conversa_criado_em_idx (migration 00011) evita o agregado
// sobre a tabela inteira.
func (q *Queries) ListarConversas(ctx context.Context, arg ListarConversasParams) ([]ListarConversasRow, error) {
	rows, err := q.db.Query(ctx, listarConversas,
		arg.Estado,
		arg.Desde,
		arg.CursorAtividade,
		arg.CursorID,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarConversasRow
	for rows.Next() {
		var i ListarConversasRow
		if err := rows.Scan(
			&i.ID,
			&i.AbertaEm,
			&i.FechadaEm,
			&i.ContatoNome,
			&i.ContatoTelefone,
			&i.ContatoChatLid,
			&i.UltimaMensagemID,
			&i.UltimaMensagemDirecao,
			&i.UltimaMensagemTipo,
			&i.UltimaMensagemTexto,
			&i.UltimaMensagemStatus,
			&i.UltimaAtividade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarMensagensDaConversa = `-- name: ListarMensagensDaConversa :many
SELECT id, direcao, tipo, texto, midia_caminho, status, criado_em
  FROM mensagem
 WHERE conversa_id = $1
   AND id > $2
   AND ($3::bigint IS NULL OR id < $3::bigint)
 ORDER BY id
 LIMIT $4
`

type ListarMensagensDaConversaParams struct {
	ConversaID int64  `json:"conversa_id"`
	DesdeID    int64  `json:"desde_id"`
	AteID      *int64 `json:"ate_id"`
	Limite     int32  `json:"limite"`
}

type ListarMensagensDaConversaRow struct {
	ID           int64            `json:"id"`
	Direcao      string           `json:"direcao"`
	Tipo         string           `json:"tipo"`
	Texto        *string          `json:"texto"`
	MidiaCaminho *string          `json:"midia_caminho"`
	Status       string           `json:"status"`
	CriadoEm     pgtype.Timestamp `json:"criado_em"`
}

// Mesmo contrato do historico do canal interno (secao G2/G3 do plano):
// desde_id/limite, ordem crescente, ultimo_id pronto para a proxima
// pagina. ate_id (nulavel) pagina PARA TRAS, para a rolagem infinita da
// timeline ao abrir uma conversa antiga.
func (q *Queries) ListarMensagensDaConversa(ctx context.Context, arg ListarMensagensDaConversaParams) ([]ListarMensagensDaConversaRow, error) {
	rows, err := q.db.Query(ctx, listarMensagensDaConversa,
		arg.ConversaID,
		arg.DesdeID,
		arg.AteID,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarMensagensDaConversaRow
	for rows.Next() {
		var i ListarMensagensDaConversaRow
		if err := rows.Scan(
			&i.ID,
			&i.Direcao,
			&i.Tipo,
			&i.Texto,
			&i.MidiaCaminho,
			&i.Status,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
