// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: disparo.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarChatLidDoLead = `-- name: AtualizarChatLidDoLead :exec
UPDATE lead SET chat_lid = $2 WHERE id = $1
`

type AtualizarChatLidDoLeadParams struct {
	ID      int64   `json:"id"`
	ChatLid *string `json:"chat_lid"`
}

func (q *Queries) AtualizarChatLidDoLead(ctx context.Context, arg AtualizarChatLidDoLeadParams) error {
	_, err := q.db.Exec(ctx, atualizarChatLidDoLead, arg.ID, arg.ChatLid)
	return err
}

const buscarDisparoPorToken = `-- name: BuscarDisparoPorToken :one
SELECT id, lead_id, template, token, enviado_em, status, nome_empreendimento FROM disparo WHERE token = $1
`

func (q *Queries) BuscarDisparoPorToken(ctx context.Context, token string) (Disparo, error) {
	row := q.db.QueryRow(ctx, buscarDisparoPorToken, token)
	var i Disparo
	err := row.Scan(
		&i.ID,
		&i.LeadID,
		&i.Template,
		&i.Token,
		&i.EnviadoEm,
		&i.Status,
		&i.NomeEmpreendimento,
	)
	return i, err
}

const buscarLeadsNaoEngajadosParaReenvio = `-- name: BuscarLeadsNaoEngajadosParaReenvio :many
WITH ultimo_disparo AS (
    SELECT DISTINCT ON (l.id)
        l.id AS lead_id,
        l.telefone_e164,
        d.template,
        d.nome_empreendimento,
        d.enviado_em AS ultimo_disparo_em,
        (SELECT count(*) FROM disparo WHERE lead_id = l.id) AS total_disparos
    FROM lead l
    JOIN disparo d ON d.lead_id = l.id
    WHERE l.estado IN ('disparado', 'clicou')
      AND l.telefone_e164 IS NOT NULL
    ORDER BY l.id, d.enviado_em DESC
)
SELECT lead_id, telefone_e164, template, nome_empreendimento, ultimo_disparo_em, total_disparos
FROM ultimo_disparo
WHERE ultimo_disparo_em <= LOCALTIMESTAMP - make_interval(secs => $1::double precision)
`

type BuscarLeadsNaoEngajadosParaReenvioRow struct {
	LeadID             int64            `json:"lead_id"`
	TelefoneE164       *string          `json:"telefone_e164"`
	Template           string           `json:"template"`
	NomeEmpreendimento *string          `json:"nome_empreendimento"`
	UltimoDisparoEm    pgtype.Timestamp `json:"ultimo_disparo_em"`
	TotalDisparos      int64            `json:"total_disparos"`
}

// candidatos ao job de reenvio (fase 11): lead que recebeu disparo ou
// clicou mas nunca chegou a 'engajado'. DISTINCT ON com ORDER BY
// enviado_em DESC pega o disparo mais recente de cada lead -- e ele que
// decide se a janela ja estourou. total_disparos alimenta o teto de
// reenvio (evitar reenviar pra sempre pra quem nunca responde), aplicado
// em Go, nao aqui -- mais facil de testar com fila falsa.
//
// A janela passou a ser filtrada aqui, no relogio do banco (P1-08). Tem de
// ser DEPOIS do DISTINCT ON, num CTE: filtrar dentro do WHERE mudaria a
// semantica -- um lead com disparo recente casaria pelo disparo ANTIGO
// dele e seria reenviado cedo demais, incomodando cliente que acabou de
// receber mensagem. O corte vale sobre o ultimo disparo, so.
func (q *Queries) BuscarLeadsNaoEngajadosParaReenvio(ctx context.Context, janelaSegundos float64) ([]BuscarLeadsNaoEngajadosParaReenvioRow, error) {
	rows, err := q.db.Query(ctx, buscarLeadsNaoEngajadosParaReenvio, janelaSegundos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarLeadsNaoEngajadosParaReenvioRow
	for rows.Next() {
		var i BuscarLeadsNaoEngajadosParaReenvioRow
		if err := rows.Scan(
			&i.LeadID,
			&i.TelefoneE164,
			&i.Template,
			&i.NomeEmpreendimento,
			&i.UltimoDisparoEm,
			&i.TotalDisparos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const criarDisparo = `-- name: CriarDisparo :one
INSERT INTO disparo (lead_id, template, token, nome_empreendimento, status)
VALUES ($1, $2, $3, $4, 'pendente')
RETURNING id, lead_id, template, token, enviado_em, status, nome_empreendimento
`

type CriarDisparoParams struct {
	LeadID             int64   `json:"lead_id"`
	Template           string  `json:"template"`
	Token              string  `json:"token"`
	NomeEmpreendimento *string `json:"nome_empreendimento"`
}

func (q *Queries) CriarDisparo(ctx context.Context, arg CriarDisparoParams) (Disparo, error) {
	row := q.db.QueryRow(ctx, criarDisparo,
		arg.LeadID,
		arg.Template,
		arg.Token,
		arg.NomeEmpreendimento,
	)
	var i Disparo
	err := row.Scan(
		&i.ID,
		&i.LeadID,
		&i.Template,
		&i.Token,
		&i.EnviadoEm,
		&i.Status,
		&i.NomeEmpreendimento,
	)
	return i, err
}

const registrarClique = `-- name: RegistrarClique :exec
INSERT INTO clique (token, lead_id, ip, user_agent)
VALUES ($1, $2, $3, $4)
`

type RegistrarCliqueParams struct {
	Token     string  `json:"token"`
	LeadID    *int64  `json:"lead_id"`
	Ip        *string `json:"ip"`
	UserAgent *string `json:"user_agent"`
}

func (q *Queries) RegistrarClique(ctx context.Context, arg RegistrarCliqueParams) error {
	_, err := q.db.Exec(ctx, registrarClique,
		arg.Token,
		arg.LeadID,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}
