// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: disparo.sql

package store

import (
	"context"
)

const atualizarChatLidDoLead = `-- name: AtualizarChatLidDoLead :exec
UPDATE lead SET chat_lid = $2 WHERE id = $1
`

type AtualizarChatLidDoLeadParams struct {
	ID      int64   `json:"id"`
	ChatLid *string `json:"chat_lid"`
}

func (q *Queries) AtualizarChatLidDoLead(ctx context.Context, arg AtualizarChatLidDoLeadParams) error {
	_, err := q.db.Exec(ctx, atualizarChatLidDoLead, arg.ID, arg.ChatLid)
	return err
}

const buscarDisparoPorToken = `-- name: BuscarDisparoPorToken :one
SELECT id, lead_id, template, token, enviado_em, status, nome_empreendimento FROM disparo WHERE token = $1
`

func (q *Queries) BuscarDisparoPorToken(ctx context.Context, token string) (Disparo, error) {
	row := q.db.QueryRow(ctx, buscarDisparoPorToken, token)
	var i Disparo
	err := row.Scan(
		&i.ID,
		&i.LeadID,
		&i.Template,
		&i.Token,
		&i.EnviadoEm,
		&i.Status,
		&i.NomeEmpreendimento,
	)
	return i, err
}

const criarDisparo = `-- name: CriarDisparo :one
INSERT INTO disparo (lead_id, template, token, nome_empreendimento, status)
VALUES ($1, $2, $3, $4, 'pendente')
RETURNING id, lead_id, template, token, enviado_em, status, nome_empreendimento
`

type CriarDisparoParams struct {
	LeadID             int64   `json:"lead_id"`
	Template           string  `json:"template"`
	Token              string  `json:"token"`
	NomeEmpreendimento *string `json:"nome_empreendimento"`
}

func (q *Queries) CriarDisparo(ctx context.Context, arg CriarDisparoParams) (Disparo, error) {
	row := q.db.QueryRow(ctx, criarDisparo,
		arg.LeadID,
		arg.Template,
		arg.Token,
		arg.NomeEmpreendimento,
	)
	var i Disparo
	err := row.Scan(
		&i.ID,
		&i.LeadID,
		&i.Template,
		&i.Token,
		&i.EnviadoEm,
		&i.Status,
		&i.NomeEmpreendimento,
	)
	return i, err
}

const registrarClique = `-- name: RegistrarClique :exec
INSERT INTO clique (token, lead_id, ip, user_agent)
VALUES ($1, $2, $3, $4)
`

type RegistrarCliqueParams struct {
	Token     string  `json:"token"`
	LeadID    *int64  `json:"lead_id"`
	Ip        *string `json:"ip"`
	UserAgent *string `json:"user_agent"`
}

func (q *Queries) RegistrarClique(ctx context.Context, arg RegistrarCliqueParams) error {
	_, err := q.db.Exec(ctx, registrarClique,
		arg.Token,
		arg.LeadID,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}
