// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dlp.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const marcarMensagemBloqueada = `-- name: MarcarMensagemBloqueada :exec
UPDATE mensagem SET status = 'bloqueada' WHERE id = $1
`

func (q *Queries) MarcarMensagemBloqueada(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, marcarMensagemBloqueada, id)
	return err
}

const registrarOcorrenciaDLP = `-- name: RegistrarOcorrenciaDLP :exec
INSERT INTO dlp_ocorrencia (mensagem_id, regra, decisao, confianca)
VALUES ($1, $2, $3, $4)
`

type RegistrarOcorrenciaDLPParams struct {
	MensagemID int64          `json:"mensagem_id"`
	Regra      string         `json:"regra"`
	Decisao    string         `json:"decisao"`
	Confianca  pgtype.Numeric `json:"confianca"`
}

// registra decisao e confianca do motor de dlp (secao 6) -- avisar e
// bloquear entram aqui para relatorio do supervisor; liberar so vai pro log.
func (q *Queries) RegistrarOcorrenciaDLP(ctx context.Context, arg RegistrarOcorrenciaDLPParams) error {
	_, err := q.db.Exec(ctx, registrarOcorrenciaDLP,
		arg.MensagemID,
		arg.Regra,
		arg.Decisao,
		arg.Confianca,
	)
	return err
}
