// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evento.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const buscarEventoPorID = `-- name: BuscarEventoPorID :one
SELECT id, chaves, aplicacao, payload, criado_em
FROM evento
WHERE id = $1
`

// Caminho rapido: o NOTIFY traz o id e esta consulta traz a linha. Devolve
// ErrNoRows se a limpeza ja passou por cima, o que so acontece com uma
// notificacao velha de mais de um dia -- nao e erro.
func (q *Queries) BuscarEventoPorID(ctx context.Context, id int64) (Evento, error) {
	row := q.db.QueryRow(ctx, buscarEventoPorID, id)
	var i Evento
	err := row.Scan(
		&i.ID,
		&i.Chaves,
		&i.Aplicacao,
		&i.Payload,
		&i.CriadoEm,
	)
	return i, err
}

const buscarUltimoIDEvento = `-- name: BuscarUltimoIDEvento :one
SELECT coalesce(max(id), 0)::bigint FROM evento
`

// Cursor inicial: uma instancia que sobe nao reproduz o historico. Quem
// estava conectado antes dela subir perdeu a conexao junto e busca o
// estado atual na reconexao do EventSource.
func (q *Queries) BuscarUltimoIDEvento(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, buscarUltimoIDEvento)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const limparEventosAntigos = `-- name: LimparEventosAntigos :execrows
DELETE FROM evento WHERE criado_em < now() - $1::interval
`

// Evento e roteamento, nao historico: quem precisa do que aconteceu tem
// `mensagem`, `mensagem_interna` e a cadeia de auditoria. Sem esta
// limpeza a tabela cresce com TODO o trafego da empresa para sempre.
func (q *Queries) LimparEventosAntigos(ctx context.Context, idade pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, limparEventosAntigos, idade)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listarEventosAPartirDe = `-- name: ListarEventosAPartirDe :many
SELECT id, chaves, aplicacao, payload, criado_em
FROM evento
WHERE id > $1
ORDER BY id
LIMIT 500
`

// Catch-up e reconciliacao: a MESMA consulta, porque a diferenca entre
// "perdi a conexao" e "confere se perdi alguma coisa" e so a frequencia.
// LIMIT para uma queda longa nao virar um SELECT de milhoes de linhas num
// unico ciclo -- o resto vem no ciclo seguinte.
//
// criado_em volta junto porque o cursor nao pode avancar ate o maior id
// visto: ids saem da sequence ANTES do commit, entao a linha 100 pode
// confirmar depois da 101. Ver escutador.varrer.
func (q *Queries) ListarEventosAPartirDe(ctx context.Context, id int64) ([]Evento, error) {
	rows, err := q.db.Query(ctx, listarEventosAPartirDe, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evento
	for rows.Next() {
		var i Evento
		if err := rows.Scan(
			&i.ID,
			&i.Chaves,
			&i.Aplicacao,
			&i.Payload,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrarEvento = `-- name: RegistrarEvento :exec

INSERT INTO evento (chaves, aplicacao, payload)
VALUES ($1, $2, $3)
`

type RegistrarEventoParams struct {
	Chaves    []string `json:"chaves"`
	Aplicacao *string  `json:"aplicacao"`
	Payload   []byte   `json:"payload"`
}

// Barramento, fase 7. A tabela `evento` e o barramento entre INSTANCIAS
// do gateway -- ver migration 00020 para por que ela existe.
// Gravado SEMPRE dentro da transacao que produziu o fato. O gatilho da
// migration 00020 dispara o pg_notify no commit; nao ha nada a chamar
// depois.
func (q *Queries) RegistrarEvento(ctx context.Context, arg RegistrarEventoParams) error {
	_, err := q.db.Exec(ctx, registrarEvento, arg.Chaves, arg.Aplicacao, arg.Payload)
	return err
}
