// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingestao.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const buscarLeadRecenteParaDedup = `-- name: BuscarLeadRecenteParaDedup :one
SELECT id, nome, telefone_e164, chat_lid, origem, empreendimento_id, lote_id, estado, corretor_id, criado_em, ad_source_id, ctwa_clid FROM lead
WHERE telefone_e164 = $1
  AND empreendimento_id IS NOT DISTINCT FROM $2
  AND criado_em >= $3
ORDER BY criado_em DESC
LIMIT 1
`

type BuscarLeadRecenteParaDedupParams struct {
	TelefoneE164     *string          `json:"telefone_e164"`
	EmpreendimentoID *int64           `json:"empreendimento_id"`
	CriadoEm         pgtype.Timestamp `json:"criado_em"`
}

// dedup da fase 11: mesmo telefone + mesmo empreendimento dentro da janela
// configuravel e o mesmo lead, nao um novo. empreendimento_id nulo em
// ambos os lados (IS NOT DISTINCT FROM) tambem casa -- origem sem
// empreendimento identificado ainda conta como duplicata pelo telefone.
func (q *Queries) BuscarLeadRecenteParaDedup(ctx context.Context, arg BuscarLeadRecenteParaDedupParams) (Lead, error) {
	row := q.db.QueryRow(ctx, buscarLeadRecenteParaDedup, arg.TelefoneE164, arg.EmpreendimentoID, arg.CriadoEm)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.TelefoneE164,
		&i.ChatLid,
		&i.Origem,
		&i.EmpreendimentoID,
		&i.LoteID,
		&i.Estado,
		&i.CorretorID,
		&i.CriadoEm,
		&i.AdSourceID,
		&i.CtwaClid,
	)
	return i, err
}

const criarLeadDeIngestao = `-- name: CriarLeadDeIngestao :one
INSERT INTO lead (nome, telefone_e164, origem, empreendimento_id, ad_source_id, ctwa_clid, estado)
VALUES ($1, $2, $3, $4, $5, $6, 'novo')
RETURNING id, nome, telefone_e164, chat_lid, origem, empreendimento_id, lote_id, estado, corretor_id, criado_em, ad_source_id, ctwa_clid
`

type CriarLeadDeIngestaoParams struct {
	Nome             *string `json:"nome"`
	TelefoneE164     *string `json:"telefone_e164"`
	Origem           *string `json:"origem"`
	EmpreendimentoID *int64  `json:"empreendimento_id"`
	AdSourceID       *string `json:"ad_source_id"`
	CtwaClid         *string `json:"ctwa_clid"`
}

// variante de CriarLead (recepcao.sql) que tambem grava empreendimento e
// atribuicao de campanha, conhecidos no momento da ingestao (fase 11) --
// chat_lid so chega depois, na primeira mensagem de whatsapp (secao 4.3).
func (q *Queries) CriarLeadDeIngestao(ctx context.Context, arg CriarLeadDeIngestaoParams) (Lead, error) {
	row := q.db.QueryRow(ctx, criarLeadDeIngestao,
		arg.Nome,
		arg.TelefoneE164,
		arg.Origem,
		arg.EmpreendimentoID,
		arg.AdSourceID,
		arg.CtwaClid,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.TelefoneE164,
		&i.ChatLid,
		&i.Origem,
		&i.EmpreendimentoID,
		&i.LoteID,
		&i.Estado,
		&i.CorretorID,
		&i.CriadoEm,
		&i.AdSourceID,
		&i.CtwaClid,
	)
	return i, err
}
