// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mensagem.sql

package store

import (
	"context"
)

const buscarConversaPorID = `-- name: BuscarConversaPorID :one
SELECT id, lead_id, corretor_id, aberta_em, fechada_em FROM conversa WHERE id = $1
`

func (q *Queries) BuscarConversaPorID(ctx context.Context, id int64) (Conversa, error) {
	row := q.db.QueryRow(ctx, buscarConversaPorID, id)
	var i Conversa
	err := row.Scan(
		&i.ID,
		&i.LeadID,
		&i.CorretorID,
		&i.AbertaEm,
		&i.FechadaEm,
	)
	return i, err
}

const criarMensagemSaida = `-- name: CriarMensagemSaida :one
INSERT INTO mensagem (conversa_id, direcao, tipo, texto, provedor)
VALUES ($1, 'saida', 'texto', $2, 'zapi')
RETURNING id, conversa_id, direcao, tipo, texto, midia_caminho, provedor, provedor_msg_id, zaap_id, status, tentativas, tentar_em, payload_bruto, criado_em, hash_anterior, hash
`

type CriarMensagemSaidaParams struct {
	ConversaID int64   `json:"conversa_id"`
	Texto      *string `json:"texto"`
}

// mensagem criada pelo CRM via POST /api/mensagens (fase 7). Direcao e
// provedor sao fixos: todo atendimento humano sai pelo numero B (zapi),
// nunca pelo numero A. So texto na v1 -- midia depende do provedor
// suportar (fase 9).
func (q *Queries) CriarMensagemSaida(ctx context.Context, arg CriarMensagemSaidaParams) (Mensagem, error) {
	row := q.db.QueryRow(ctx, criarMensagemSaida, arg.ConversaID, arg.Texto)
	var i Mensagem
	err := row.Scan(
		&i.ID,
		&i.ConversaID,
		&i.Direcao,
		&i.Tipo,
		&i.Texto,
		&i.MidiaCaminho,
		&i.Provedor,
		&i.ProvedorMsgID,
		&i.ZaapID,
		&i.Status,
		&i.Tentativas,
		&i.TentarEm,
		&i.PayloadBruto,
		&i.CriadoEm,
		&i.HashAnterior,
		&i.Hash,
	)
	return i, err
}
