// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mensagem.sql

package store

import (
	"context"
)

const buscarConversaPorID = `-- name: BuscarConversaPorID :one
SELECT id, lead_id, corretor_id, aberta_em, fechada_em FROM conversa WHERE id = $1
`

func (q *Queries) BuscarConversaPorID(ctx context.Context, id int64) (Conversa, error) {
	row := q.db.QueryRow(ctx, buscarConversaPorID, id)
	var i Conversa
	err := row.Scan(
		&i.ID,
		&i.LeadID,
		&i.CorretorID,
		&i.AbertaEm,
		&i.FechadaEm,
	)
	return i, err
}

const criarMensagemSaida = `-- name: CriarMensagemSaida :one
INSERT INTO mensagem (conversa_id, direcao, tipo, texto, midia_caminho, provedor, aplicacao_id)
VALUES (
    $1,
    'saida',
    $2,
    $3,
    $4,
    'zapi',
    $5
)
RETURNING id, conversa_id, direcao, tipo, texto, midia_caminho, provedor, provedor_msg_id, zaap_id, status, tentativas, tentar_em, payload_bruto, criado_em, hash_anterior, hash, ultimo_erro, aplicacao_id
`

type CriarMensagemSaidaParams struct {
	ConversaID   int64   `json:"conversa_id"`
	Tipo         string  `json:"tipo"`
	Texto        *string `json:"texto"`
	MidiaCaminho *string `json:"midia_caminho"`
	AplicacaoID  *int64  `json:"aplicacao_id"`
}

// mensagem criada pelo CRM via POST /api/mensagens (fase 7). Direcao e
// provedor seguem fixos: todo atendimento humano sai pelo numero B (zapi),
// nunca pelo numero A.
//
// tipo e midia_caminho passaram a vir do chamador (fase 3). Antes o tipo
// era 'texto' fixo aqui: o outbox ja sabia mandar midia desde a fase 9,
// mas nao havia como o CRM pedir isso -- a legenda ate chegava, o arquivo
// nao. O handler valida o tipo antes; o CHECK do schema e a rede de
// seguranca.
//
// aplicacao_id e a procedencia (barramento, fase 1): vem do token
// autenticado, nunca do corpo. Nulavel enquanto o caminho legado
// (ExigirTokenServico) existir -- vira NOT NULL na fase 8.
func (q *Queries) CriarMensagemSaida(ctx context.Context, arg CriarMensagemSaidaParams) (Mensagem, error) {
	row := q.db.QueryRow(ctx, criarMensagemSaida,
		arg.ConversaID,
		arg.Tipo,
		arg.Texto,
		arg.MidiaCaminho,
		arg.AplicacaoID,
	)
	var i Mensagem
	err := row.Scan(
		&i.ID,
		&i.ConversaID,
		&i.Direcao,
		&i.Tipo,
		&i.Texto,
		&i.MidiaCaminho,
		&i.Provedor,
		&i.ProvedorMsgID,
		&i.ZaapID,
		&i.Status,
		&i.Tentativas,
		&i.TentarEm,
		&i.PayloadBruto,
		&i.CriadoEm,
		&i.HashAnterior,
		&i.Hash,
		&i.UltimoErro,
		&i.AplicacaoID,
	)
	return i, err
}
