// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mensagem_interna.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarHashMensagemInterna = `-- name: AtualizarHashMensagemInterna :exec
UPDATE mensagem_interna SET hash_anterior = $2, hash = $3 WHERE id = $1
`

type AtualizarHashMensagemInternaParams struct {
	ID           int64   `json:"id"`
	HashAnterior *string `json:"hash_anterior"`
	Hash         *string `json:"hash"`
}

func (q *Queries) AtualizarHashMensagemInterna(ctx context.Context, arg AtualizarHashMensagemInternaParams) error {
	_, err := q.db.Exec(ctx, atualizarHashMensagemInterna, arg.ID, arg.HashAnterior, arg.Hash)
	return err
}

const criarMensagemInterna = `-- name: CriarMensagemInterna :one

INSERT INTO mensagem_interna (
    canal_ref_id, aplicacao_id, remetente_externo,
    conteudo_cifrado, cifra_alg, cifra_versao
)
SELECT
    c.id, c.aplicacao_id, $1,
    $2, $3, $4
FROM canal c
WHERE c.aplicacao_id = $5
  AND c.canal_externo = $6
RETURNING id, canal_ref_id, criado_em
`

type CriarMensagemInternaParams struct {
	RemetenteExterno *string `json:"remetente_externo"`
	ConteudoCifrado  []byte  `json:"conteudo_cifrado"`
	CifraAlg         *string `json:"cifra_alg"`
	CifraVersao      *int32  `json:"cifra_versao"`
	AplicacaoID      int64   `json:"aplicacao_id"`
	CanalExterno     string  `json:"canal_externo"`
}

type CriarMensagemInternaRow struct {
	ID         int64            `json:"id"`
	CanalRefID *int64           `json:"canal_ref_id"`
	CriadoEm   pgtype.Timestamp `json:"criado_em"`
}

// Barramento, fase 5. Como em canal.sql, TODA query aqui e escopada por
// aplicacao_id dentro do proprio SQL -- o escopo e o WHERE, nunca uma
// checagem no Go que um handler novo possa esquecer.
// O canal vem por (aplicacao, canal_externo) numa subconsulta escopada, e
// nao como id: assim um id de canal de outra aplicacao, adivinhado ou
// vazado, nao consegue gravar mensagem aqui. Zero linhas significa canal
// inexistente PARA ESTA APLICACAO -- o handler responde 404, igual a
// canal que nao existe, para nao confirmar a existencia do canal alheio.
//
// aplicacao_id sai da propria linha de canal, e nao de um parametro: sao
// necessariamente a mesma, e derivar evita a divergencia silenciosa de um
// dia alguem passar as duas coisas e errar uma.
func (q *Queries) CriarMensagemInterna(ctx context.Context, arg CriarMensagemInternaParams) (CriarMensagemInternaRow, error) {
	row := q.db.QueryRow(ctx, criarMensagemInterna,
		arg.RemetenteExterno,
		arg.ConteudoCifrado,
		arg.CifraAlg,
		arg.CifraVersao,
		arg.AplicacaoID,
		arg.CanalExterno,
	)
	var i CriarMensagemInternaRow
	err := row.Scan(&i.ID, &i.CanalRefID, &i.CriadoEm)
	return i, err
}

const listarMensagensDoCanal = `-- name: ListarMensagensDoCanal :many
SELECT mi.id, mi.remetente_externo, mi.conteudo_cifrado,
       mi.cifra_alg, mi.cifra_versao, mi.criado_em
FROM mensagem_interna mi
JOIN canal c ON c.id = mi.canal_ref_id
WHERE c.aplicacao_id = $1
  AND c.canal_externo = $2
  AND mi.id > $3
ORDER BY mi.id
LIMIT $4
`

type ListarMensagensDoCanalParams struct {
	AplicacaoID  int64  `json:"aplicacao_id"`
	CanalExterno string `json:"canal_externo"`
	DesdeID      int64  `json:"desde_id"`
	Limite       int32  `json:"limite"`
}

type ListarMensagensDoCanalRow struct {
	ID               int64            `json:"id"`
	RemetenteExterno *string          `json:"remetente_externo"`
	ConteudoCifrado  []byte           `json:"conteudo_cifrado"`
	CifraAlg         *string          `json:"cifra_alg"`
	CifraVersao      *int32           `json:"cifra_versao"`
	CriadoEm         pgtype.Timestamp `json:"criado_em"`
}

// Historico paginado (secao 6.3). Devolve o ciphertext como esta gravado
// -- byte a byte o que a aplicacao mandou. Nao ha, e nao pode haver,
// nenhuma transformacao do conteudo neste caminho.
//
// Escopo por aplicacao e o unico controle de acesso que existe aqui: quem
// decide se AQUELE usuario pode ler o canal e a aplicacao, antes de
// chamar (secao 1). O gateway nao consulta canal_assinante para decidir
// leitura -- canal_assinante e lista de ENTREGA, nao de permissao, e
// usa-la para autorizar seria inventar um modelo de permissao aqui.
//
// Ordem crescente por id: e assim que a aplicacao avanca o desde_id dela
// e retoma de onde parou depois de uma queda do SSE.
func (q *Queries) ListarMensagensDoCanal(ctx context.Context, arg ListarMensagensDoCanalParams) ([]ListarMensagensDoCanalRow, error) {
	rows, err := q.db.Query(ctx, listarMensagensDoCanal,
		arg.AplicacaoID,
		arg.CanalExterno,
		arg.DesdeID,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarMensagensDoCanalRow
	for rows.Next() {
		var i ListarMensagensDoCanalRow
		if err := rows.Scan(
			&i.ID,
			&i.RemetenteExterno,
			&i.ConteudoCifrado,
			&i.CifraAlg,
			&i.CifraVersao,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
