// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alertum struct {
	ID       int64            `json:"id"`
	Tipo     string           `json:"tipo"`
	Detalhe  *string          `json:"detalhe"`
	CriadoEm pgtype.Timestamp `json:"criado_em"`
}

type Aplicacao struct {
	ID        int64            `json:"id"`
	Codigo    string           `json:"codigo"`
	Nome      string           `json:"nome"`
	TokenHash string           `json:"token_hash"`
	Ativo     bool             `json:"ativo"`
	CriadoEm  pgtype.Timestamp `json:"criado_em"`
}

type Canal struct {
	ID           int64            `json:"id"`
	AplicacaoID  int64            `json:"aplicacao_id"`
	CanalExterno string           `json:"canal_externo"`
	CriadoEm     pgtype.Timestamp `json:"criado_em"`
}

type CanalAssinante struct {
	CanalID        int64            `json:"canal_id"`
	DestinoExterno string           `json:"destino_externo"`
	CriadoEm       pgtype.Timestamp `json:"criado_em"`
}

type CanalInterno struct {
	ID     int64  `json:"id"`
	Nome   string `json:"nome"`
	Tipo   string `json:"tipo"`
	LeadID *int64 `json:"lead_id"`
}

type Clique struct {
	ID        int64            `json:"id"`
	Token     string           `json:"token"`
	LeadID    *int64           `json:"lead_id"`
	Ip        *string          `json:"ip"`
	UserAgent *string          `json:"user_agent"`
	ClicadoEm pgtype.Timestamp `json:"clicado_em"`
}

type Conversa struct {
	ID         int64            `json:"id"`
	LeadID     int64            `json:"lead_id"`
	CorretorID *int64           `json:"corretor_id"`
	AbertaEm   pgtype.Timestamp `json:"aberta_em"`
	FechadaEm  pgtype.Timestamp `json:"fechada_em"`
}

type Disparo struct {
	ID                 int64            `json:"id"`
	LeadID             int64            `json:"lead_id"`
	Template           string           `json:"template"`
	Token              string           `json:"token"`
	EnviadoEm          pgtype.Timestamp `json:"enviado_em"`
	Status             string           `json:"status"`
	NomeEmpreendimento *string          `json:"nome_empreendimento"`
}

type DlpOcorrencium struct {
	ID         int64            `json:"id"`
	MensagemID int64            `json:"mensagem_id"`
	Regra      string           `json:"regra"`
	Decisao    string           `json:"decisao"`
	Confianca  pgtype.Numeric   `json:"confianca"`
	CriadoEm   pgtype.Timestamp `json:"criado_em"`
}

type Equipe struct {
	ID   int64  `json:"id"`
	Nome string `json:"nome"`
}

type Evento struct {
	ID        int64              `json:"id"`
	Chaves    []string           `json:"chaves"`
	Aplicacao *string            `json:"aplicacao"`
	Payload   []byte             `json:"payload"`
	CriadoEm  pgtype.Timestamptz `json:"criado_em"`
}

type Faq struct {
	ID               int64  `json:"id"`
	Pergunta         string `json:"pergunta"`
	Resposta         string `json:"resposta"`
	OrigemMensagemID *int64 `json:"origem_mensagem_id"`
}

type Lead struct {
	ID                 int64            `json:"id"`
	Nome               *string          `json:"nome"`
	TelefoneE164       *string          `json:"telefone_e164"`
	ChatLid            *string          `json:"chat_lid"`
	Origem             *string          `json:"origem"`
	EmpreendimentoID   *int64           `json:"empreendimento_id"`
	LoteID             *int64           `json:"lote_id"`
	Estado             string           `json:"estado"`
	CorretorID         *int64           `json:"corretor_id"`
	CriadoEm           pgtype.Timestamp `json:"criado_em"`
	AdSourceID         *string          `json:"ad_source_id"`
	CtwaClid           *string          `json:"ctwa_clid"`
	EstagioComercial   string           `json:"estagio_comercial"`
	EstagioEntrouEm    pgtype.Timestamp `json:"estagio_entrou_em"`
	Valor              pgtype.Numeric   `json:"valor"`
	NomeEmpreendimento *string          `json:"nome_empreendimento"`
	Tipologia          *string          `json:"tipologia"`
	FormaPagamento     *string          `json:"forma_pagamento"`
	ProximoPassoTexto  *string          `json:"proximo_passo_texto"`
	ProximoPassoEm     pgtype.Timestamp `json:"proximo_passo_em"`
	Notas              *string          `json:"notas"`
}

type LeadPayloadBruto struct {
	ID         int64            `json:"id"`
	LeadID     *int64           `json:"lead_id"`
	Origem     string           `json:"origem"`
	Payload    []byte           `json:"payload"`
	RecebidoEm pgtype.Timestamp `json:"recebido_em"`
}

type Mensagem struct {
	ID            int64            `json:"id"`
	ConversaID    int64            `json:"conversa_id"`
	Direcao       string           `json:"direcao"`
	Tipo          string           `json:"tipo"`
	Texto         *string          `json:"texto"`
	MidiaCaminho  *string          `json:"midia_caminho"`
	Provedor      string           `json:"provedor"`
	ProvedorMsgID *string          `json:"provedor_msg_id"`
	ZaapID        *string          `json:"zaap_id"`
	Status        string           `json:"status"`
	Tentativas    int32            `json:"tentativas"`
	TentarEm      pgtype.Timestamp `json:"tentar_em"`
	PayloadBruto  []byte           `json:"payload_bruto"`
	CriadoEm      pgtype.Timestamp `json:"criado_em"`
	HashAnterior  *string          `json:"hash_anterior"`
	Hash          *string          `json:"hash"`
	UltimoErro    *string          `json:"ultimo_erro"`
	AplicacaoID   *int64           `json:"aplicacao_id"`
}

type MensagemInterna struct {
	ID               int64            `json:"id"`
	CriadoEm         pgtype.Timestamp `json:"criado_em"`
	AplicacaoID      int64            `json:"aplicacao_id"`
	CanalRefID       int64            `json:"canal_ref_id"`
	RemetenteExterno string           `json:"remetente_externo"`
	ConteudoCifrado  []byte           `json:"conteudo_cifrado"`
	CifraAlg         string           `json:"cifra_alg"`
	CifraVersao      int32            `json:"cifra_versao"`
	HashAnterior     *string          `json:"hash_anterior"`
	Hash             *string          `json:"hash"`
}

type MidiaBiblioteca struct {
	ID        int64   `json:"id"`
	Nome      string  `json:"nome"`
	Caminho   string  `json:"caminho"`
	Categoria *string `json:"categoria"`
	Ativo     bool    `json:"ativo"`
}

type Parametro struct {
	Chave     string  `json:"chave"`
	Valor     *string `json:"valor"`
	Descricao *string `json:"descricao"`
}

type Presenca struct {
	UsuarioID         int64            `json:"usuario_id"`
	Disponivel        bool             `json:"disponivel"`
	UltimaAtividadeEm pgtype.Timestamp `json:"ultima_atividade_em"`
}

type ProvedorSaude struct {
	ID           int64            `json:"id"`
	Provedor     string           `json:"provedor"`
	Conectado    bool             `json:"conectado"`
	VerificadoEm pgtype.Timestamp `json:"verificado_em"`
	LatenciaMs   *int32           `json:"latencia_ms"`
	UltimoErro   *string          `json:"ultimo_erro"`
}

type PushSubscription struct {
	ID         int64            `json:"id"`
	CorretorID int64            `json:"corretor_id"`
	Endpoint   string           `json:"endpoint"`
	P256dh     string           `json:"p256dh"`
	Auth       string           `json:"auth"`
	CriadoEm   pgtype.Timestamp `json:"criado_em"`
}

type SlaEvento struct {
	ID         int64            `json:"id"`
	LeadID     int64            `json:"lead_id"`
	CorretorID *int64           `json:"corretor_id"`
	Tipo       string           `json:"tipo"`
	OcorridoEm pgtype.Timestamp `json:"ocorrido_em"`
	Detalhe    *string          `json:"detalhe"`
}

type Usuario struct {
	ID        int64            `json:"id"`
	Nome      string           `json:"nome"`
	Email     string           `json:"email"`
	SenhaHash string           `json:"senha_hash"`
	Perfil    string           `json:"perfil"`
	Ativo     bool             `json:"ativo"`
	CriadoEm  pgtype.Timestamp `json:"criado_em"`
}

type UsuarioEquipe struct {
	UsuarioID int64 `json:"usuario_id"`
	EquipeID  int64 `json:"equipe_id"`
}
