// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CanalInterno struct {
	ID     int64  `json:"id"`
	Nome   string `json:"nome"`
	Tipo   string `json:"tipo"`
	LeadID *int64 `json:"lead_id"`
}

type Clique struct {
	ID        int64            `json:"id"`
	Token     string           `json:"token"`
	LeadID    *int64           `json:"lead_id"`
	Ip        *string          `json:"ip"`
	UserAgent *string          `json:"user_agent"`
	ClicadoEm pgtype.Timestamp `json:"clicado_em"`
}

type Conversa struct {
	ID         int64            `json:"id"`
	LeadID     int64            `json:"lead_id"`
	CorretorID *int64           `json:"corretor_id"`
	AbertaEm   pgtype.Timestamp `json:"aberta_em"`
	FechadaEm  pgtype.Timestamp `json:"fechada_em"`
}

type Disparo struct {
	ID                 int64            `json:"id"`
	LeadID             int64            `json:"lead_id"`
	Template           string           `json:"template"`
	Token              string           `json:"token"`
	EnviadoEm          pgtype.Timestamp `json:"enviado_em"`
	Status             string           `json:"status"`
	NomeEmpreendimento *string          `json:"nome_empreendimento"`
}

type DlpOcorrencium struct {
	ID         int64            `json:"id"`
	MensagemID int64            `json:"mensagem_id"`
	Regra      string           `json:"regra"`
	Decisao    string           `json:"decisao"`
	Confianca  pgtype.Numeric   `json:"confianca"`
	CriadoEm   pgtype.Timestamp `json:"criado_em"`
}

type Equipe struct {
	ID   int64  `json:"id"`
	Nome string `json:"nome"`
}

type Faq struct {
	ID               int64  `json:"id"`
	Pergunta         string `json:"pergunta"`
	Resposta         string `json:"resposta"`
	OrigemMensagemID *int64 `json:"origem_mensagem_id"`
}

type Lead struct {
	ID               int64            `json:"id"`
	Nome             *string          `json:"nome"`
	TelefoneE164     *string          `json:"telefone_e164"`
	ChatLid          *string          `json:"chat_lid"`
	Origem           *string          `json:"origem"`
	EmpreendimentoID *int64           `json:"empreendimento_id"`
	LoteID           *int64           `json:"lote_id"`
	Estado           string           `json:"estado"`
	CorretorID       *int64           `json:"corretor_id"`
	CriadoEm         pgtype.Timestamp `json:"criado_em"`
}

type LeadPayloadBruto struct {
	ID         int64            `json:"id"`
	LeadID     *int64           `json:"lead_id"`
	Origem     string           `json:"origem"`
	Payload    []byte           `json:"payload"`
	RecebidoEm pgtype.Timestamp `json:"recebido_em"`
}

type Mensagem struct {
	ID            int64            `json:"id"`
	ConversaID    int64            `json:"conversa_id"`
	Direcao       string           `json:"direcao"`
	Tipo          string           `json:"tipo"`
	Texto         *string          `json:"texto"`
	MidiaCaminho  *string          `json:"midia_caminho"`
	Provedor      string           `json:"provedor"`
	ProvedorMsgID *string          `json:"provedor_msg_id"`
	ZaapID        *string          `json:"zaap_id"`
	Status        string           `json:"status"`
	Tentativas    int32            `json:"tentativas"`
	TentarEm      pgtype.Timestamp `json:"tentar_em"`
	PayloadBruto  []byte           `json:"payload_bruto"`
	CriadoEm      pgtype.Timestamp `json:"criado_em"`
	HashAnterior  *string          `json:"hash_anterior"`
	Hash          *string          `json:"hash"`
	UltimoErro    *string          `json:"ultimo_erro"`
}

type MensagemInterna struct {
	ID        int64            `json:"id"`
	CanalID   int64            `json:"canal_id"`
	UsuarioID int64            `json:"usuario_id"`
	Texto     string           `json:"texto"`
	CriadoEm  pgtype.Timestamp `json:"criado_em"`
}

type MidiaBiblioteca struct {
	ID        int64   `json:"id"`
	Nome      string  `json:"nome"`
	Caminho   string  `json:"caminho"`
	Categoria *string `json:"categoria"`
	Ativo     bool    `json:"ativo"`
}

type Parametro struct {
	Chave     string  `json:"chave"`
	Valor     *string `json:"valor"`
	Descricao *string `json:"descricao"`
}

type Presenca struct {
	UsuarioID         int64            `json:"usuario_id"`
	Disponivel        bool             `json:"disponivel"`
	UltimaAtividadeEm pgtype.Timestamp `json:"ultima_atividade_em"`
}

type ProvedorSaude struct {
	ID           int64            `json:"id"`
	Provedor     string           `json:"provedor"`
	Conectado    bool             `json:"conectado"`
	VerificadoEm pgtype.Timestamp `json:"verificado_em"`
	LatenciaMs   *int32           `json:"latencia_ms"`
	UltimoErro   *string          `json:"ultimo_erro"`
}

type SlaEvento struct {
	ID         int64            `json:"id"`
	LeadID     int64            `json:"lead_id"`
	CorretorID *int64           `json:"corretor_id"`
	Tipo       string           `json:"tipo"`
	OcorridoEm pgtype.Timestamp `json:"ocorrido_em"`
}

type Usuario struct {
	ID        int64            `json:"id"`
	Nome      string           `json:"nome"`
	Email     string           `json:"email"`
	SenhaHash string           `json:"senha_hash"`
	Perfil    string           `json:"perfil"`
	Ativo     bool             `json:"ativo"`
	CriadoEm  pgtype.Timestamp `json:"criado_em"`
}

type UsuarioEquipe struct {
	UsuarioID int64 `json:"usuario_id"`
	EquipeID  int64 `json:"equipe_id"`
}
