// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const marcarMensagemEnviada = `-- name: MarcarMensagemEnviada :exec
UPDATE mensagem
SET status = 'enviada', provedor_msg_id = $2, zaap_id = $3
WHERE id = $1
`

type MarcarMensagemEnviadaParams struct {
	ID            int64   `json:"id"`
	ProvedorMsgID *string `json:"provedor_msg_id"`
	ZaapID        *string `json:"zaap_id"`
}

func (q *Queries) MarcarMensagemEnviada(ctx context.Context, arg MarcarMensagemEnviadaParams) error {
	_, err := q.db.Exec(ctx, marcarMensagemEnviada, arg.ID, arg.ProvedorMsgID, arg.ZaapID)
	return err
}

const marcarMensagemFalhaDefinitiva = `-- name: MarcarMensagemFalhaDefinitiva :exec
UPDATE mensagem
SET status = 'falha', tentativas = tentativas + 1
WHERE id = $1
`

func (q *Queries) MarcarMensagemFalhaDefinitiva(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, marcarMensagemFalhaDefinitiva, id)
	return err
}

const marcarMensagemParaRetentativa = `-- name: MarcarMensagemParaRetentativa :exec
UPDATE mensagem
SET status = 'pendente', tentativas = tentativas + 1, tentar_em = $2
WHERE id = $1
`

type MarcarMensagemParaRetentativaParams struct {
	ID       int64            `json:"id"`
	TentarEm pgtype.Timestamp `json:"tentar_em"`
}

func (q *Queries) MarcarMensagemParaRetentativa(ctx context.Context, arg MarcarMensagemParaRetentativaParams) error {
	_, err := q.db.Exec(ctx, marcarMensagemParaRetentativa, arg.ID, arg.TentarEm)
	return err
}

const resetarMensagensPresasEmEnvio = `-- name: ResetarMensagensPresasEmEnvio :exec
UPDATE mensagem
SET status = 'pendente'
WHERE status = 'enviando'
`

// roda no start do worker -- kill -9 durante o envio nao deve deixar
// mensagem orfa em 'enviando' depois do restart.
func (q *Queries) ResetarMensagensPresasEmEnvio(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetarMensagensPresasEmEnvio)
	return err
}

const selecionarPendentesParaEnvio = `-- name: SelecionarPendentesParaEnvio :many
WITH selecionadas AS (
    SELECT id FROM mensagem
    WHERE status = 'pendente' AND direcao = 'saida' AND tentar_em <= LOCALTIMESTAMP
    ORDER BY criado_em
    FOR UPDATE SKIP LOCKED
    LIMIT $1
), atualizadas AS (
    UPDATE mensagem m
    SET status = 'enviando'
    FROM selecionadas s
    WHERE m.id = s.id
    RETURNING m.id, m.conversa_id, m.texto, m.tentativas
)
SELECT a.id, a.conversa_id, a.texto, a.tentativas, lead.chat_lid, lead.telefone_e164, c.corretor_id
FROM atualizadas a
JOIN conversa c ON c.id = a.conversa_id
JOIN lead ON lead.id = c.lead_id
`

type SelecionarPendentesParaEnvioRow struct {
	ID           int64   `json:"id"`
	ConversaID   int64   `json:"conversa_id"`
	Texto        *string `json:"texto"`
	Tentativas   int32   `json:"tentativas"`
	ChatLid      *string `json:"chat_lid"`
	TelefoneE164 *string `json:"telefone_e164"`
	CorretorID   *int64  `json:"corretor_id"`
}

// outbox: a fila e a propria tabela mensagem filtrada por status (secao 7).
// FOR UPDATE SKIP LOCKED evita que dois workers peguem a mesma mensagem.
// conversa_id e corretor_id alimentam a publicacao do evento sse apos o
// envio (fase 7) -- sem eles o worker nao sabe pra qual corretor notificar.
func (q *Queries) SelecionarPendentesParaEnvio(ctx context.Context, limit int32) ([]SelecionarPendentesParaEnvioRow, error) {
	rows, err := q.db.Query(ctx, selecionarPendentesParaEnvio, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelecionarPendentesParaEnvioRow
	for rows.Next() {
		var i SelecionarPendentesParaEnvioRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversaID,
			&i.Texto,
			&i.Tentativas,
			&i.ChatLid,
			&i.TelefoneE164,
			&i.CorretorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
