// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parametro.sql

package store

import (
	"context"
)

const buscarParametro = `-- name: BuscarParametro :one
SELECT chave, valor, descricao
FROM parametro
WHERE chave = $1
`

func (q *Queries) BuscarParametro(ctx context.Context, chave string) (Parametro, error) {
	row := q.db.QueryRow(ctx, buscarParametro, chave)
	var i Parametro
	err := row.Scan(&i.Chave, &i.Valor, &i.Descricao)
	return i, err
}

const definirParametro = `-- name: DefinirParametro :exec
INSERT INTO parametro (chave, valor, descricao)
VALUES ($1, $2, $3)
ON CONFLICT (chave) DO UPDATE SET valor = EXCLUDED.valor
`

type DefinirParametroParams struct {
	Chave     string  `json:"chave"`
	Valor     *string `json:"valor"`
	Descricao *string `json:"descricao"`
}

func (q *Queries) DefinirParametro(ctx context.Context, arg DefinirParametroParams) error {
	_, err := q.db.Exec(ctx, definirParametro, arg.Chave, arg.Valor, arg.Descricao)
	return err
}
