// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parametro.sql

package store

import (
	"context"
)

const buscarParametro = `-- name: BuscarParametro :one
SELECT chave, valor, descricao
FROM parametro
WHERE chave = $1
`

func (q *Queries) BuscarParametro(ctx context.Context, chave string) (Parametro, error) {
	row := q.db.QueryRow(ctx, buscarParametro, chave)
	var i Parametro
	err := row.Scan(&i.Chave, &i.Valor, &i.Descricao)
	return i, err
}

const definirParametro = `-- name: DefinirParametro :exec
INSERT INTO parametro (chave, valor, descricao)
VALUES ($1, $2, $3)
ON CONFLICT (chave) DO UPDATE SET valor = EXCLUDED.valor
`

type DefinirParametroParams struct {
	Chave     string  `json:"chave"`
	Valor     *string `json:"valor"`
	Descricao *string `json:"descricao"`
}

func (q *Queries) DefinirParametro(ctx context.Context, arg DefinirParametroParams) error {
	_, err := q.db.Exec(ctx, definirParametro, arg.Chave, arg.Valor, arg.Descricao)
	return err
}

const purgarPayloadBrutoAntigo = `-- name: PurgarPayloadBrutoAntigo :execrows
DELETE FROM lead_payload_bruto
WHERE recebido_em < LOCALTIMESTAMP - make_interval(secs => $1::double precision)
`

// Retencao (fase 6). lead_payload_bruto guarda o payload cru de TODO
// webhook (diretriz 7: gravar antes de parsear), incluindo o que foi
// descartado por fromMe/grupo. Cresce com o trafego e nunca era limpo.
//
// O payload serve para depurar recepcao e para reprocessar uma mensagem
// mal interpretada -- as duas coisas com validade curta. O dado de negocio
// ja esta em lead/conversa/mensagem e nao depende disto.
func (q *Queries) PurgarPayloadBrutoAntigo(ctx context.Context, retencaoSegundos float64) (int64, error) {
	result, err := q.db.Exec(ctx, purgarPayloadBrutoAntigo, retencaoSegundos)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgarProvedorSaudeAntigo = `-- name: PurgarProvedorSaudeAntigo :execrows
DELETE FROM provedor_saude
WHERE id IN (
    SELECT id FROM (
        SELECT id,
               verificado_em,
               conectado,
               lag(conectado) OVER (PARTITION BY provedor ORDER BY id) AS anterior
        FROM provedor_saude
    ) t
    WHERE t.verificado_em < LOCALTIMESTAMP - make_interval(secs => $1::double precision)
      AND t.anterior IS NOT DISTINCT FROM t.conectado
)
`

// Retencao (fase 6). O monitor grava 1 linha a cada 30s: 2.880 por dia,
// ~1 milhao por ano, para uma tabela cuja unica consulta e "qual a leitura
// mais recente". Historico antigo de saude nao tem consumidor.
//
// PRESERVA as transicoes de estado (conectado != anterior): e delas que
// sai "quando a instancia caiu", que foi exatamente a pergunta que se
// precisou responder em 2026-08-13. Apagar tudo por idade destruiria a
// unica informacao com valor retroativo da tabela.
func (q *Queries) PurgarProvedorSaudeAntigo(ctx context.Context, retencaoSegundos float64) (int64, error) {
	result, err := q.db.Exec(ctx, purgarProvedorSaudeAntigo, retencaoSegundos)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
