// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recepcao.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarLeadDoPayloadBruto = `-- name: AtualizarLeadDoPayloadBruto :exec
UPDATE lead_payload_bruto SET lead_id = $2 WHERE id = $1
`

type AtualizarLeadDoPayloadBrutoParams struct {
	ID     int64  `json:"id"`
	LeadID *int64 `json:"lead_id"`
}

func (q *Queries) AtualizarLeadDoPayloadBruto(ctx context.Context, arg AtualizarLeadDoPayloadBrutoParams) error {
	_, err := q.db.Exec(ctx, atualizarLeadDoPayloadBruto, arg.ID, arg.LeadID)
	return err
}

const atualizarStatusMensagemPorProvedorMsgID = `-- name: AtualizarStatusMensagemPorProvedorMsgID :execrows
UPDATE mensagem SET status = $2 WHERE provedor_msg_id = $1
`

type AtualizarStatusMensagemPorProvedorMsgIDParams struct {
	ProvedorMsgID *string `json:"provedor_msg_id"`
	Status        string  `json:"status"`
}

func (q *Queries) AtualizarStatusMensagemPorProvedorMsgID(ctx context.Context, arg AtualizarStatusMensagemPorProvedorMsgIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, atualizarStatusMensagemPorProvedorMsgID, arg.ProvedorMsgID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const buscarCliqueRecentePorLead = `-- name: BuscarCliqueRecentePorLead :one
SELECT id, token, lead_id, ip, user_agent, clicado_em FROM clique
WHERE lead_id = $1 AND clicado_em >= $2
ORDER BY clicado_em DESC
LIMIT 1
`

type BuscarCliqueRecentePorLeadParams struct {
	LeadID    *int64           `json:"lead_id"`
	ClicadoEm pgtype.Timestamp `json:"clicado_em"`
}

func (q *Queries) BuscarCliqueRecentePorLead(ctx context.Context, arg BuscarCliqueRecentePorLeadParams) (Clique, error) {
	row := q.db.QueryRow(ctx, buscarCliqueRecentePorLead, arg.LeadID, arg.ClicadoEm)
	var i Clique
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.LeadID,
		&i.Ip,
		&i.UserAgent,
		&i.ClicadoEm,
	)
	return i, err
}

const buscarConversaAbertaPorLead = `-- name: BuscarConversaAbertaPorLead :one
SELECT id, lead_id, corretor_id, aberta_em, fechada_em FROM conversa WHERE lead_id = $1 AND fechada_em IS NULL ORDER BY aberta_em DESC LIMIT 1
`

func (q *Queries) BuscarConversaAbertaPorLead(ctx context.Context, leadID int64) (Conversa, error) {
	row := q.db.QueryRow(ctx, buscarConversaAbertaPorLead, leadID)
	var i Conversa
	err := row.Scan(
		&i.ID,
		&i.LeadID,
		&i.CorretorID,
		&i.AbertaEm,
		&i.FechadaEm,
	)
	return i, err
}

const buscarLeadPorChatLid = `-- name: BuscarLeadPorChatLid :one
SELECT id, nome, telefone_e164, chat_lid, origem, empreendimento_id, lote_id, estado, corretor_id, criado_em FROM lead WHERE chat_lid = $1
`

func (q *Queries) BuscarLeadPorChatLid(ctx context.Context, chatLid *string) (Lead, error) {
	row := q.db.QueryRow(ctx, buscarLeadPorChatLid, chatLid)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.TelefoneE164,
		&i.ChatLid,
		&i.Origem,
		&i.EmpreendimentoID,
		&i.LoteID,
		&i.Estado,
		&i.CorretorID,
		&i.CriadoEm,
	)
	return i, err
}

const buscarLeadPorTelefone = `-- name: BuscarLeadPorTelefone :one
SELECT id, nome, telefone_e164, chat_lid, origem, empreendimento_id, lote_id, estado, corretor_id, criado_em FROM lead WHERE telefone_e164 = $1
`

func (q *Queries) BuscarLeadPorTelefone(ctx context.Context, telefoneE164 *string) (Lead, error) {
	row := q.db.QueryRow(ctx, buscarLeadPorTelefone, telefoneE164)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.TelefoneE164,
		&i.ChatLid,
		&i.Origem,
		&i.EmpreendimentoID,
		&i.LoteID,
		&i.Estado,
		&i.CorretorID,
		&i.CriadoEm,
	)
	return i, err
}

const buscarLeadPorTokenNoTexto = `-- name: BuscarLeadPorTokenNoTexto :one
SELECT l.id, l.nome, l.telefone_e164, l.chat_lid, l.origem, l.empreendimento_id, l.lote_id, l.estado, l.corretor_id, l.criado_em FROM lead l
JOIN disparo d ON d.lead_id = l.id
WHERE d.token <> '' AND position(d.token IN $1::text) > 0
ORDER BY d.enviado_em DESC
LIMIT 1
`

// assume que o token de disparo e uma string suficientemente unica para
// nao dar falso positivo por substring (ver secao 6 -- token pre-preenchido
// no texto do disparo).
func (q *Queries) BuscarLeadPorTokenNoTexto(ctx context.Context, texto string) (Lead, error) {
	row := q.db.QueryRow(ctx, buscarLeadPorTokenNoTexto, texto)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.TelefoneE164,
		&i.ChatLid,
		&i.Origem,
		&i.EmpreendimentoID,
		&i.LoteID,
		&i.Estado,
		&i.CorretorID,
		&i.CriadoEm,
	)
	return i, err
}

const criarConversa = `-- name: CriarConversa :one
INSERT INTO conversa (lead_id) VALUES ($1) RETURNING id, lead_id, corretor_id, aberta_em, fechada_em
`

func (q *Queries) CriarConversa(ctx context.Context, leadID int64) (Conversa, error) {
	row := q.db.QueryRow(ctx, criarConversa, leadID)
	var i Conversa
	err := row.Scan(
		&i.ID,
		&i.LeadID,
		&i.CorretorID,
		&i.AbertaEm,
		&i.FechadaEm,
	)
	return i, err
}

const criarLead = `-- name: CriarLead :one
INSERT INTO lead (nome, telefone_e164, chat_lid, origem, estado)
VALUES ($1, $2, $3, $4, 'novo')
RETURNING id, nome, telefone_e164, chat_lid, origem, empreendimento_id, lote_id, estado, corretor_id, criado_em
`

type CriarLeadParams struct {
	Nome         *string `json:"nome"`
	TelefoneE164 *string `json:"telefone_e164"`
	ChatLid      *string `json:"chat_lid"`
	Origem       *string `json:"origem"`
}

func (q *Queries) CriarLead(ctx context.Context, arg CriarLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, criarLead,
		arg.Nome,
		arg.TelefoneE164,
		arg.ChatLid,
		arg.Origem,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.TelefoneE164,
		&i.ChatLid,
		&i.Origem,
		&i.EmpreendimentoID,
		&i.LoteID,
		&i.Estado,
		&i.CorretorID,
		&i.CriadoEm,
	)
	return i, err
}

const inserirLeadPayloadBruto = `-- name: InserirLeadPayloadBruto :one
INSERT INTO lead_payload_bruto (lead_id, origem, payload)
VALUES (NULL, $1, $2)
RETURNING id
`

type InserirLeadPayloadBrutoParams struct {
	Origem  string `json:"origem"`
	Payload []byte `json:"payload"`
}

// grava o payload bruto antes de qualquer parse (secao 10, diretriz 7).
// lead_id comeca nulo -- so sabemos o lead depois do matcher.
func (q *Queries) InserirLeadPayloadBruto(ctx context.Context, arg InserirLeadPayloadBrutoParams) (int64, error) {
	row := q.db.QueryRow(ctx, inserirLeadPayloadBruto, arg.Origem, arg.Payload)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const inserirMensagemEntrada = `-- name: InserirMensagemEntrada :one
INSERT INTO mensagem (conversa_id, direcao, tipo, texto, midia_caminho, provedor, provedor_msg_id, payload_bruto)
VALUES ($1, 'entrada', $2, $3, $4, $5, $6, $7)
ON CONFLICT (provedor_msg_id) WHERE provedor_msg_id IS NOT NULL DO NOTHING
RETURNING id
`

type InserirMensagemEntradaParams struct {
	ConversaID    int64   `json:"conversa_id"`
	Tipo          string  `json:"tipo"`
	Texto         *string `json:"texto"`
	MidiaCaminho  *string `json:"midia_caminho"`
	Provedor      string  `json:"provedor"`
	ProvedorMsgID *string `json:"provedor_msg_id"`
	PayloadBruto  []byte  `json:"payload_bruto"`
}

// ON CONFLICT casa com o indice unico parcial mensagem_provedor_msg_id_idx
// (migration 00003) -- webhook duplicado da z-api nao duplica mensagem.
func (q *Queries) InserirMensagemEntrada(ctx context.Context, arg InserirMensagemEntradaParams) (int64, error) {
	row := q.db.QueryRow(ctx, inserirMensagemEntrada,
		arg.ConversaID,
		arg.Tipo,
		arg.Texto,
		arg.MidiaCaminho,
		arg.Provedor,
		arg.ProvedorMsgID,
		arg.PayloadBruto,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const registrarSaudeProvedor = `-- name: RegistrarSaudeProvedor :exec
INSERT INTO provedor_saude (provedor, conectado, latencia_ms, ultimo_erro)
VALUES ($1, $2, $3, $4)
`

type RegistrarSaudeProvedorParams struct {
	Provedor   string  `json:"provedor"`
	Conectado  bool    `json:"conectado"`
	LatenciaMs *int32  `json:"latencia_ms"`
	UltimoErro *string `json:"ultimo_erro"`
}

func (q *Queries) RegistrarSaudeProvedor(ctx context.Context, arg RegistrarSaudeProvedorParams) error {
	_, err := q.db.Exec(ctx, registrarSaudeProvedor,
		arg.Provedor,
		arg.Conectado,
		arg.LatenciaMs,
		arg.UltimoErro,
	)
	return err
}
